// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace MY_APPLICATION.Controllers
{
    public partial class HomeController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected HomeController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ContentResult learn09()
        {
            return new T4MVC_System_Web_Mvc_ContentResult(Area, Name, ActionNames.learn09);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult learn10()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.learn10);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ContentResult Action3()
        {
            return new T4MVC_System_Web_Mvc_ContentResult(Area, Name, ActionNames.Action3);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ContentResult Learn15()
        {
            return new T4MVC_System_Web_Mvc_ContentResult(Area, Name, ActionNames.Learn15);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public HomeController Actions { get { return MVC.Home; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Home";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Home";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string learn09 = "learn09";
            public readonly string Action1 = "Action1";
            public readonly string Action2 = "Action2";
            public readonly string learn10 = "learn10";
            public readonly string Action3 = "Action3";
            public readonly string learn11 = "learn11";
            public readonly string Action4 = "Action4";
            public readonly string Action5 = "Action5";
            public readonly string learn12 = "learn12";
            public readonly string Aboutus = "Aboutus";
            public readonly string About = "About";
            public readonly string Learn13 = "Learn13";
            public readonly string Learn14 = "Learn14";
            public readonly string Learn15 = "Learn15";
            public readonly string Learn16 = "Learn16";
            public readonly string Learn1370 = "Learn1370";
            public readonly string learn18 = "learn18";
            public readonly string learn19 = "learn19";
            public readonly string learn20 = "learn20";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string learn09 = "learn09";
            public const string Action1 = "Action1";
            public const string Action2 = "Action2";
            public const string learn10 = "learn10";
            public const string Action3 = "Action3";
            public const string learn11 = "learn11";
            public const string Action4 = "Action4";
            public const string Action5 = "Action5";
            public const string learn12 = "learn12";
            public const string Aboutus = "Aboutus";
            public const string About = "About";
            public const string Learn13 = "Learn13";
            public const string Learn14 = "Learn14";
            public const string Learn15 = "Learn15";
            public const string Learn16 = "Learn16";
            public const string Learn1370 = "Learn1370";
            public const string learn18 = "learn18";
            public const string learn19 = "learn19";
            public const string learn20 = "learn20";
        }


        static readonly ActionParamsClass_learn09 s_params_learn09 = new ActionParamsClass_learn09();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_learn09 learn09Params { get { return s_params_learn09; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_learn09
        {
            public readonly string name = "name";
        }
        static readonly ActionParamsClass_learn10 s_params_learn10 = new ActionParamsClass_learn10();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_learn10 learn10Params { get { return s_params_learn10; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_learn10
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Action3 s_params_Action3 = new ActionParamsClass_Action3();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Action3 Action3Params { get { return s_params_Action3; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Action3
        {
            public readonly string firstName = "firstName";
            public readonly string lastName = "lastName";
        }
        static readonly ActionParamsClass_Learn15 s_params_Learn15 = new ActionParamsClass_Learn15();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Learn15 Learn15Params { get { return s_params_Learn15; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Learn15
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
            }
            public readonly string Index = "~/Views/Home/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_HomeController : MY_APPLICATION.Controllers.HomeController
    {
        public T4MVC_HomeController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ViewResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void learn09Override(T4MVC_System_Web_Mvc_ContentResult callInfo, string name);

        [NonAction]
        public override System.Web.Mvc.ContentResult learn09(string name)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ContentResult(Area, Name, ActionNames.learn09);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "name", name);
            learn09Override(callInfo, name);
            return callInfo;
        }

        [NonAction]
        partial void Action1Override(T4MVC_System_Web_Mvc_ContentResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ContentResult Action1()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ContentResult(Area, Name, ActionNames.Action1);
            Action1Override(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void Action2Override(T4MVC_System_Web_Mvc_ContentResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ContentResult Action2()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ContentResult(Area, Name, ActionNames.Action2);
            Action2Override(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void learn10Override(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult learn10(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.learn10);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            learn10Override(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void Action3Override(T4MVC_System_Web_Mvc_ContentResult callInfo, string firstName, string lastName);

        [NonAction]
        public override System.Web.Mvc.ContentResult Action3(string firstName, string lastName)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ContentResult(Area, Name, ActionNames.Action3);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "firstName", firstName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lastName", lastName);
            Action3Override(callInfo, firstName, lastName);
            return callInfo;
        }

        [NonAction]
        partial void learn11Override(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult learn11()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.learn11);
            learn11Override(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void Action4Override(T4MVC_System_Web_Mvc_ContentResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ContentResult Action4()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ContentResult(Area, Name, ActionNames.Action4);
            Action4Override(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void Action5Override(T4MVC_System_Web_Mvc_ContentResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ContentResult Action5()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ContentResult(Area, Name, ActionNames.Action5);
            Action5Override(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void learn12Override(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult learn12()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.learn12);
            learn12Override(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void AboutusOverride(T4MVC_System_Web_Mvc_RedirectResult callInfo);

        [NonAction]
        public override System.Web.Mvc.RedirectResult Aboutus()
        {
            var callInfo = new T4MVC_System_Web_Mvc_RedirectResult(Area, Name, ActionNames.Aboutus);
            AboutusOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void AboutOverride(T4MVC_System_Web_Mvc_ContentResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ContentResult About()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ContentResult(Area, Name, ActionNames.About);
            AboutOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void Learn13Override(T4MVC_System_Web_Mvc_ContentResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ContentResult Learn13()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ContentResult(Area, Name, ActionNames.Learn13);
            Learn13Override(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void Learn14Override(T4MVC_System_Web_Mvc_ContentResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ContentResult Learn14()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ContentResult(Area, Name, ActionNames.Learn14);
            Learn14Override(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void Learn15Override(T4MVC_System_Web_Mvc_ContentResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ContentResult Learn15(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ContentResult(Area, Name, ActionNames.Learn15);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            Learn15Override(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void Learn16Override(T4MVC_System_Web_Mvc_ContentResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ContentResult Learn16()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ContentResult(Area, Name, ActionNames.Learn16);
            Learn16Override(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void Learn1370Override(T4MVC_System_Web_Mvc_ContentResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ContentResult Learn1370()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ContentResult(Area, Name, ActionNames.Learn1370);
            Learn1370Override(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void learn18Override(T4MVC_System_Web_Mvc_ContentResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ContentResult learn18()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ContentResult(Area, Name, ActionNames.learn18);
            learn18Override(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void learn19Override(T4MVC_System_Web_Mvc_JsonResult callInfo);

        [NonAction]
        public override System.Web.Mvc.JsonResult learn19()
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.learn19);
            learn19Override(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void learn20Override(T4MVC_System_Web_Mvc_FileResult callInfo);

        [NonAction]
        public override System.Web.Mvc.FileResult learn20()
        {
            var callInfo = new T4MVC_System_Web_Mvc_FileResult(Area, Name, ActionNames.learn20);
            learn20Override(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
