// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace MY_APPLICATION.Controllers
{
    public partial class LearningValidationController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected LearningValidationController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult CheckUsername()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CheckUsername);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult CheckEmailAddress()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CheckEmailAddress);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public LearningValidationController Actions { get { return MVC.LearningValidation; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "LearningValidation";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "LearningValidation";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Learn01 = "Learn01";
            public readonly string Learn02 = "Learn02";
            public readonly string Learn03 = "Learn03";
            public readonly string Learn04 = "Learn04";
            public readonly string Learn05 = "Learn05";
            public readonly string Learn06 = "Learn06";
            public readonly string Learn07 = "Learn07";
            public readonly string Learn08 = "Learn08";
            public readonly string CheckUsername = "CheckUsername";
            public readonly string CheckEmailAddress = "CheckEmailAddress";
            public readonly string Learn09 = "Learn09";
            public readonly string Learn10 = "Learn10";
            public readonly string Learn11 = "Learn11";
            public readonly string Learn12 = "Learn12";
            public readonly string Learn13 = "Learn13";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Learn01 = "Learn01";
            public const string Learn02 = "Learn02";
            public const string Learn03 = "Learn03";
            public const string Learn04 = "Learn04";
            public const string Learn05 = "Learn05";
            public const string Learn06 = "Learn06";
            public const string Learn07 = "Learn07";
            public const string Learn08 = "Learn08";
            public const string CheckUsername = "CheckUsername";
            public const string CheckEmailAddress = "CheckEmailAddress";
            public const string Learn09 = "Learn09";
            public const string Learn10 = "Learn10";
            public const string Learn11 = "Learn11";
            public const string Learn12 = "Learn12";
            public const string Learn13 = "Learn13";
        }


        static readonly ActionParamsClass_Learn01 s_params_Learn01 = new ActionParamsClass_Learn01();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Learn01 Learn01Params { get { return s_params_Learn01; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Learn01
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Learn02 s_params_Learn02 = new ActionParamsClass_Learn02();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Learn02 Learn02Params { get { return s_params_Learn02; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Learn02
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Learn03 s_params_Learn03 = new ActionParamsClass_Learn03();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Learn03 Learn03Params { get { return s_params_Learn03; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Learn03
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Learn04 s_params_Learn04 = new ActionParamsClass_Learn04();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Learn04 Learn04Params { get { return s_params_Learn04; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Learn04
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Learn05 s_params_Learn05 = new ActionParamsClass_Learn05();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Learn05 Learn05Params { get { return s_params_Learn05; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Learn05
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Learn06 s_params_Learn06 = new ActionParamsClass_Learn06();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Learn06 Learn06Params { get { return s_params_Learn06; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Learn06
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Learn07 s_params_Learn07 = new ActionParamsClass_Learn07();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Learn07 Learn07Params { get { return s_params_Learn07; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Learn07
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Learn08 s_params_Learn08 = new ActionParamsClass_Learn08();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Learn08 Learn08Params { get { return s_params_Learn08; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Learn08
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_CheckUsername s_params_CheckUsername = new ActionParamsClass_CheckUsername();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CheckUsername CheckUsernameParams { get { return s_params_CheckUsername; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CheckUsername
        {
            public readonly string username = "username";
        }
        static readonly ActionParamsClass_CheckEmailAddress s_params_CheckEmailAddress = new ActionParamsClass_CheckEmailAddress();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CheckEmailAddress CheckEmailAddressParams { get { return s_params_CheckEmailAddress; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CheckEmailAddress
        {
            public readonly string emailAddress = "emailAddress";
        }
        static readonly ActionParamsClass_Learn09 s_params_Learn09 = new ActionParamsClass_Learn09();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Learn09 Learn09Params { get { return s_params_Learn09; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Learn09
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Learn10 s_params_Learn10 = new ActionParamsClass_Learn10();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Learn10 Learn10Params { get { return s_params_Learn10; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Learn10
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Learn11 s_params_Learn11 = new ActionParamsClass_Learn11();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Learn11 Learn11Params { get { return s_params_Learn11; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Learn11
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Learn12 s_params_Learn12 = new ActionParamsClass_Learn12();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Learn12 Learn12Params { get { return s_params_Learn12; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Learn12
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Learn13 s_params_Learn13 = new ActionParamsClass_Learn13();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Learn13 Learn13Params { get { return s_params_Learn13; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Learn13
        {
            public readonly string model = "model";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
                public readonly string Learn01 = "Learn01";
                public readonly string Learn02 = "Learn02";
                public readonly string Learn03 = "Learn03";
                public readonly string Learn04 = "Learn04";
                public readonly string Learn05 = "Learn05";
                public readonly string Learn06 = "Learn06";
                public readonly string Learn07 = "Learn07";
                public readonly string Learn08 = "Learn08";
                public readonly string Learn09 = "Learn09";
                public readonly string Learn10 = "Learn10";
                public readonly string Learn11 = "Learn11";
                public readonly string Learn12 = "Learn12";
                public readonly string Learn13 = "Learn13";
            }
            public readonly string Index = "~/Views/LearningValidation/Index.cshtml";
            public readonly string Learn01 = "~/Views/LearningValidation/Learn01.cshtml";
            public readonly string Learn02 = "~/Views/LearningValidation/Learn02.cshtml";
            public readonly string Learn03 = "~/Views/LearningValidation/Learn03.cshtml";
            public readonly string Learn04 = "~/Views/LearningValidation/Learn04.cshtml";
            public readonly string Learn05 = "~/Views/LearningValidation/Learn05.cshtml";
            public readonly string Learn06 = "~/Views/LearningValidation/Learn06.cshtml";
            public readonly string Learn07 = "~/Views/LearningValidation/Learn07.cshtml";
            public readonly string Learn08 = "~/Views/LearningValidation/Learn08.cshtml";
            public readonly string Learn09 = "~/Views/LearningValidation/Learn09.cshtml";
            public readonly string Learn10 = "~/Views/LearningValidation/Learn10.cshtml";
            public readonly string Learn11 = "~/Views/LearningValidation/Learn11.cshtml";
            public readonly string Learn12 = "~/Views/LearningValidation/Learn12.cshtml";
            public readonly string Learn13 = "~/Views/LearningValidation/Learn13.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_LearningValidationController : MY_APPLICATION.Controllers.LearningValidationController
    {
        public T4MVC_LearningValidationController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void Learn01Override(T4MVC_System_Web_Mvc_ViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ViewResult Learn01()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Learn01);
            Learn01Override(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void Learn01Override(T4MVC_System_Web_Mvc_ActionResult callInfo, Models.Validation.Learn01 model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Learn01(Models.Validation.Learn01 model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Learn01);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            Learn01Override(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void Learn02Override(T4MVC_System_Web_Mvc_ViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ViewResult Learn02()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Learn02);
            Learn02Override(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void Learn02Override(T4MVC_System_Web_Mvc_ActionResult callInfo, Models.Validation.Learn02 model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Learn02(Models.Validation.Learn02 model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Learn02);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            Learn02Override(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void Learn03Override(T4MVC_System_Web_Mvc_ViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ViewResult Learn03()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Learn03);
            Learn03Override(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void Learn03Override(T4MVC_System_Web_Mvc_ActionResult callInfo, Models.Validation.Learn03 model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Learn03(Models.Validation.Learn03 model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Learn03);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            Learn03Override(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void Learn04Override(T4MVC_System_Web_Mvc_ViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ViewResult Learn04()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Learn04);
            Learn04Override(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void Learn04Override(T4MVC_System_Web_Mvc_ActionResult callInfo, Models.Validation.Learn04 model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Learn04(Models.Validation.Learn04 model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Learn04);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            Learn04Override(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void Learn05Override(T4MVC_System_Web_Mvc_ViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ViewResult Learn05()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Learn05);
            Learn05Override(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void Learn05Override(T4MVC_System_Web_Mvc_ActionResult callInfo, Models.Validation.Learn05 model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Learn05(Models.Validation.Learn05 model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Learn05);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            Learn05Override(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void Learn06Override(T4MVC_System_Web_Mvc_ViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ViewResult Learn06()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Learn06);
            Learn06Override(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void Learn06Override(T4MVC_System_Web_Mvc_ActionResult callInfo, Models.Validation.Learn06 model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Learn06(Models.Validation.Learn06 model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Learn06);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            Learn06Override(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void Learn07Override(T4MVC_System_Web_Mvc_ViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ViewResult Learn07()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Learn07);
            Learn07Override(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void Learn07Override(T4MVC_System_Web_Mvc_ActionResult callInfo, Models.Validation.Learn07 model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Learn07(Models.Validation.Learn07 model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Learn07);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            Learn07Override(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void Learn08Override(T4MVC_System_Web_Mvc_ViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ViewResult Learn08()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Learn08);
            Learn08Override(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void Learn08Override(T4MVC_System_Web_Mvc_ActionResult callInfo, Models.Validation.Learn08 model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Learn08(Models.Validation.Learn08 model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Learn08);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            Learn08Override(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void CheckUsernameOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string username);

        [NonAction]
        public override System.Web.Mvc.JsonResult CheckUsername(string username)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CheckUsername);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "username", username);
            CheckUsernameOverride(callInfo, username);
            return callInfo;
        }

        [NonAction]
        partial void CheckEmailAddressOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string emailAddress);

        [NonAction]
        public override System.Web.Mvc.JsonResult CheckEmailAddress(string emailAddress)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CheckEmailAddress);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "emailAddress", emailAddress);
            CheckEmailAddressOverride(callInfo, emailAddress);
            return callInfo;
        }

        [NonAction]
        partial void Learn09Override(T4MVC_System_Web_Mvc_ViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ViewResult Learn09()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Learn09);
            Learn09Override(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void Learn09Override(T4MVC_System_Web_Mvc_ActionResult callInfo, Models.Validation.learn09 model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Learn09(Models.Validation.learn09 model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Learn09);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            Learn09Override(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void Learn10Override(T4MVC_System_Web_Mvc_ViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ViewResult Learn10()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Learn10);
            Learn10Override(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void Learn10Override(T4MVC_System_Web_Mvc_ActionResult callInfo, Models.Validation.Learn10 model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Learn10(Models.Validation.Learn10 model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Learn10);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            Learn10Override(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void Learn11Override(T4MVC_System_Web_Mvc_ViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ViewResult Learn11()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Learn11);
            Learn11Override(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void Learn11Override(T4MVC_System_Web_Mvc_ActionResult callInfo, Models.Validation.Learn11 model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Learn11(Models.Validation.Learn11 model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Learn11);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            Learn11Override(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void Learn12Override(T4MVC_System_Web_Mvc_ViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ViewResult Learn12()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Learn12);
            Learn12Override(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void Learn12Override(T4MVC_System_Web_Mvc_ActionResult callInfo, Models.Validation.Learn12 model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Learn12(Models.Validation.Learn12 model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Learn12);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            Learn12Override(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void Learn13Override(T4MVC_System_Web_Mvc_ViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ViewResult Learn13()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Learn13);
            Learn13Override(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void Learn13Override(T4MVC_System_Web_Mvc_ActionResult callInfo, Models.Validation.Learn13 model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Learn13(Models.Validation.Learn13 model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Learn13);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            Learn13Override(callInfo, model);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
